#!/bin/sh

# Set mdev
echo /sbin/mdev > /proc/sys/kernel/hotplug
/sbin/mdev -s && echo "mdev is ok......"

# create console and null node for nfsroot
#mknod -m 600 /dev/console c 5 1
#mknod -m 666 /dev/null c 1 3

# Set Global Environment
export PATH=/bin:/sbin:/usr/bin:/usr/sbin
export PATH=/system/bin:$PATH
export LD_LIBRARY_PATH=/system/lib
export LD_LIBRARY_PATH=/thirdlib:$LD_LIBRARY_PATH

# networking
ifconfig lo up
#ifconfig eth0 192.168.1.80

# Set the system time from the hardware clock
#hwclock -s

#set the GPIO PC13 to high, make the USB Disk can be use
cd /sys/class/gpio
echo 77 > export       #申请GPIO
cd gpio77
echo out > direction   #设置为输出模式
echo 0 > active_low    #value是0,表示低电平。value是1,表示高电平
echo 1 > value         #设置电平（输出模式）

# Mount driver partition
mount -t squashfs /dev/mtdblock3 /driver

# Mount system partition
mount -t jffs2 /dev/mtdblock4 /system

# Mount backup partition
#mount -t jffs2 /dev/mtdblock5 /backupk

# Mount backup partition
#mount -t jffs2 /dev/mtdblock6 /backupd

# Mount backup partition
mount -t jffs2 /dev/mtdblock7 /backupa

# Mount configs partition
mount -t jffs2 /dev/mtdblock8 /configs

# Mount params partition
mount -t jffs2 /dev/mtdblock9 /params

# Format system patition if it is invalid
if [ ! -f /system/.system ]; then
    echo "WARNING: Missing /system/.system. Is appfs partition corrupted?"
fi

shadow_date=$(date -r /etc/shadow "+%b %d, %Y")

echo "*****************************************"
echo "*   root password updated by wyzehack   *"
echo "*****************************************"

# Wait for SD card to be mounted
sleep 3

if [ -b /dev/mmcblk0p1 ]; then
    echo "Trying to load wyze hack from SD card..."
    mkdir -p /tmp/mmcblk0p1
    mount /dev/mmcblk0p1 /tmp/mmcblk0p1
fi

WYZEHACKS="/tmp/mmcblk0p1/wyzehacks/wyzehacks.bin"
if [ -f $WYZEHACKS ]; then
    echo "Loading Wyze hacks..."
    $WYZEHACKS &
else
    # Run init script
    APP_INIT=/system/init/app_init.sh
    if [ -f $APP_INIT ]; then
        chmod a+x $APP_INIT
        $APP_INIT &
    fi
fi
